# This is a basic workflow to help you get started with Actions

name: Debug 

on:
 workflow_dispatch:
  inputs:
     environment:
        description: 'Environment to run tests against'
        type: environment
        required: true 
       

env :
   BUILD_VERSION : ${{ github.event.inputs.version }}
   VERSION :  "2.0"
   ENVIRONMENT : "LOCAL-DEV"
   TARGET_RTF : "target-rtf"
   APPLICATION_NAME : "application-name"
   PROXY_HOST : "proxy-host"
   PROXY_PORT : "proxy-port"
   KEY_VAULT_NAME: "per-azkv"
   NEXUS-USER-NAME: "nexus-user-name"
   NEXUS-USER-PASSWORD : "nexus-user-password"
   CONNECTED-APP-CLIENT-ID_KV : "connected-app-client-id-kv"
   CONNECTED-APP-SECRET-ID_KV : "connected-app-secret-id-kv"
   CERT_NAME : "cert-name"
   CERT_FILE_NAME : "cert-file-name"

   
    
jobs:     
  deploy:
    runs-on: ubuntu-latest
    environment : ${{github.event.inputs.environment}} 
    steps:
#    - name: Echo
#      run: |
#        echo ${{ secrets.AZURE_CREDENTIALS }}
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
#    - name : Download Key Valut Secrets   
#      uses: Azure/get-keyvault-secrets@v1
#      with: 
#        keyvault: $KEY_VAULT_NAME
#        secrets: 'ks-test'
#      id: secretAction
    - name : Download Key Vault Secrets
      run: |
        myTest=My Test
        echo "$myTest" >> "$GITHUB_OUTPUT"
      id: myVars
    - name: Echo
      run: |
        echo ${{steps.myVars.outputs.myVar}}
        echo ${{steps.myVars.outputs.myVar2}}
#    - name: Download certificate
#      run : |
#          #az keyvault secret download --file $CERT_FILE_NAME --vault-name $KEY_VAULT_NAME --name $CERT_NAME  --encoding base64
#          #CONNECTED-APP-CLIENT-ID= $(az keyvault secret show --name $CONNECTED-APP-CLIENT-ID_KV  --vault-name $KEY_VAULT_NAME --query value -o tsv)
#          az keyvault secret show --name $CONNECTED-APP-CLIENT-ID_KV --vault-name $KEY_VAULT_NAME$
#          // client password , nexsus user and variables 

