# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
     environment:
        description: 'Environment to run Test, Build and Deploy'
        type: environment
        required: true
    
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo ${{ github.event.inputs.environment }}
          echo ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: Checkout this repo
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      #TO DO - add auth secerts and replace them
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8
